# Generated by Django 3.0.8 on 2020-07-01 09:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'College',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 7, 1, 14, 54, 39, 476083))),
                ('college', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.College', verbose_name='College')),
            ],
        ),
    ]
