# Generated by Django 3.0.8 on 2020-07-01 15:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student'},
        ),
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 1, 20, 35, 19, 564747)),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('pic', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 7, 1, 20, 35, 19, 565747))),
                ('stu_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Student', verbose_name='Student')),
            ],
        ),
    ]
